name: grisette
version: 0.1.0.0
synopsis: Symbolic evaluation as a library
description: |
  Grisette is a reusable symbolic evaluation library for Haskell. By
  translating programs into constraints, Grisette can help the development of
  program reasoning tools, including verification, synthesis, and more.
  .
  This package exports all constructs you need for building a symbolic evaluation
  tool from [grisette-core](https://hackage.haskell.org/package/grisette-core), [grisette-symir](https://hackage.haskell.org/package/grisette-symir),
  and [grisette-backend-sbv](https://hackage.haskell.org/package/grisette-backend-sbv) packages.
  .
  For more details, please checkout the README.
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-haskell
copyright: "2021-2022 Sirui Lu"
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- grisette-symir == 0.1.0.0
- grisette-backend-sbv == 0.1.0.0

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src
