name: grisette
version: 0.12.0.0
synopsis: Symbolic evaluation as a library
description: "Grisette is a reusable symbolic evaluation library for Haskell. By\ntranslating programs into constraints, Grisette can help the development of\nprogram reasoning tools, including verification, synthesis, and more.\n.\nThe \"Grisette\" module exports all the core APIs for building a symbolic\nevaluation tool. A high-level overview of the module structures are available\nthere.\n.\nA detailed introduction to Grisette is available at \"Grisette.Core\". More\nlifted libraries are provided in @Grisette.Lib.*@ modules.\n.\nThe \"Grisette.Unified\" module offers an experimental unified interface for\nsymbolic and concrete evaluation. This module should be imported qualified.\n.\nFor more details, please checkout the README and \n[tutorials](https://github.com/lsrcz/grisette/tree/main/tutorials).\n"
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu, Rastislav Bodík"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette
copyright: "2021-2024 Sirui Lu"
extra-source-files:
  - CHANGELOG.md
  - README.md
tested-with:
  - GHC == 8.10.7
  - GHC == 9.0.2
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.6
  - GHC == 9.8.4
  - GHC == 9.10.1
  - GHC == 9.12.1
dependencies:
  - base >= 4.14 && < 5
  - hashable >= 1.3 && < 1.6
  - mtl >= 2.2.2 && < 2.4
  - transformers >= 0.5.6.2 && < 0.7
  - generic-deriving >= 1.14.1 && < 1.15
  - bytestring >= 0.10.12 && < 0.13
  - containers >= 0.5.7 && < 0.9
  - unordered-containers >= 0.2.17 && < 0.3
  - template-haskell >= 2.16 && < 2.24
  - deepseq >= 1.4.4 && < 1.6
  - loch-th >= 0.2.2 && < 0.3
  - th-compat >= 0.1.2 && < 0.2
  - th-abstraction >= 0.4 && < 0.8
  - array >= 0.5.4 && < 0.6
  - sbv >= 8.17 && < 12
  - parallel >= 3.2.2 && < 3.3
  - text >= 1.2.4.1 && < 2.2
  - QuickCheck >= 2.14 && < 2.16
  - prettyprinter >= 1.5.0 && < 1.8
  - async >= 2.2.2 && < 2.3
  - stm >= 2.5 && < 2.6
  - libBF >= 0.6.3 && < 0.7
  - th-lift-instances >= 0.1.16 && < 0.2
  - vector >= 0.12.1.2 && < 0.14
  - atomic-primops >= 0.8.3 && < 0.9
  - cereal >= 0.5.8.1 && < 0.6
  - cereal-text >= 0.1.0.2 && < 0.2
  - binary >= 0.8.8.0 && < 0.9
  - bytes >= 0.17.1 && < 0.18
flags: {optimize: {description: "Compile with O2 optimization", manual: False, default: True}}
when:
  - condition: flag(optimize)
    then:
      ghc-options:
        - -O2
    else:
      ghc-options: -O0
  - condition: impl(ghc >= 9.2)
    then:
      ghc-prof-options:
        - -finfo-table-map
        - -fdistinct-constructor-tables
    else:
      ghc-prof-options: []
ghc-options:
  - -Wextra
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wno-x-partial
  - -Wno-unrecognised-warning-flags
library:
  source-dirs: src
  other-modules:
    - Grisette.Internal.Internal.Decl.Core.Data.Class.ExtractSym
    - Grisette.Internal.Internal.Decl.Core.Data.Class.PPrint
    - Grisette.Internal.Internal.Decl.Core.Data.Class.ToCon
    - Grisette.Internal.Internal.Decl.Core.Data.Class.SafeDiv
    - Grisette.Internal.Internal.Decl.Core.Data.Class.SubstSym
    - Grisette.Internal.Internal.Decl.Core.Data.Class.ToSym
    - Grisette.Internal.Internal.Decl.Core.Data.Class.SymEq
    - Grisette.Internal.Internal.Decl.Core.Data.Class.TryMerge
    - Grisette.Internal.Internal.Decl.Core.Data.Class.SymOrd
    - Grisette.Internal.Internal.Decl.Core.Data.Class.Solver
    - Grisette.Internal.Internal.Decl.Core.Data.Class.SimpleMergeable
    - Grisette.Internal.Internal.Decl.Core.Data.Class.Mergeable
    - Grisette.Internal.Internal.Decl.Core.Data.Class.EvalSym
    - Grisette.Internal.Internal.Decl.Core.Data.UnionBase
    - Grisette.Internal.Internal.Decl.Core.Control.Monad.Union
    - Grisette.Internal.Internal.Decl.SymPrim.AllSyms
    - Grisette.Internal.Internal.Decl.Unified.UnifiedBV
    - Grisette.Internal.Internal.Decl.Unified.UnifiedBool
    - Grisette.Internal.Internal.Decl.Unified.BVFPConversion
    - Grisette.Internal.Internal.Decl.Unified.Class.UnifiedSymEq
    - Grisette.Internal.Internal.Decl.Unified.Class.UnifiedSymOrd
    - Grisette.Internal.Internal.Decl.Unified.Class.UnifiedSimpleMergeable
    - Grisette.Internal.Internal.Decl.Unified.Class.UnifiedITEOp
    - Grisette.Internal.Internal.Decl.Unified.UnifiedFP
    - Grisette.Internal.Internal.Decl.Unified.EvalMode
    - Grisette.Internal.Internal.Decl.Unified.FPFPConversion
    - Grisette.Internal.Internal.Impl.Core.Data.Class.ExtractSym
    - Grisette.Internal.Internal.Impl.Core.Data.Class.PPrint
    - Grisette.Internal.Internal.Impl.Core.Data.Class.ToCon
    - Grisette.Internal.Internal.Impl.Core.Data.Class.SafeDiv
    - Grisette.Internal.Internal.Impl.Core.Data.Class.SubstSym
    - Grisette.Internal.Internal.Impl.Core.Data.Class.ToSym
    - Grisette.Internal.Internal.Impl.Core.Data.Class.SymEq
    - Grisette.Internal.Internal.Impl.Core.Data.Class.TryMerge
    - Grisette.Internal.Internal.Impl.Core.Data.Class.SymOrd
    - Grisette.Internal.Internal.Impl.Core.Data.Class.Solver
    - Grisette.Internal.Internal.Impl.Core.Data.Class.SimpleMergeable
    - Grisette.Internal.Internal.Impl.Core.Data.Class.Mergeable
    - Grisette.Internal.Internal.Impl.Core.Data.Class.EvalSym
    - Grisette.Internal.Internal.Impl.Core.Data.UnionBase
    - Grisette.Internal.Internal.Impl.Core.Control.Monad.Union
    - Grisette.Internal.Internal.Impl.SymPrim.AllSyms
    - Grisette.Internal.Internal.Impl.Unified.UnifiedBV
    - Grisette.Internal.Internal.Impl.Unified.UnifiedBool
    - Grisette.Internal.Internal.Impl.Unified.BVFPConversion
    - Grisette.Internal.Internal.Impl.Unified.Class.UnifiedSymEq
    - Grisette.Internal.Internal.Impl.Unified.Class.UnifiedSymOrd
    - Grisette.Internal.Internal.Impl.Unified.Class.UnifiedSimpleMergeable
    - Grisette.Internal.Internal.Impl.Unified.Class.UnifiedITEOp
    - Grisette.Internal.Internal.Impl.Unified.UnifiedFP
    - Grisette.Internal.Internal.Impl.Unified.EvalMode
    - Grisette.Internal.Internal.Impl.Unified.FPFPConversion
tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette
      - test-framework >= 0.8.2 && < 0.9
      - test-framework-hunit >= 0.3.0.2 && < 0.4
      - test-framework-quickcheck2 >= 0.3.0.5 && < 0.4
      - HUnit >= 1.6 && < 1.7
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wredundant-constraints
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - grisette
      - doctest >= 0.18.2 && < 0.25
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
