name: grisette
version: 0.8.0.0
synopsis: Symbolic evaluation as a library
description: |
  Grisette is a reusable symbolic evaluation library for Haskell. By
  translating programs into constraints, Grisette can help the development of
  program reasoning tools, including verification, synthesis, and more.
  .
  The "Grisette" module exports all the core APIs for building a symbolic
  evaluation tool. A high-level overview of the module structures are available
  there.
  .
  A detailed introduction to Grisette is available at "Grisette.Core". More
  lifted libraries are provided in @Grisette.Lib.*@ modules.
  .
  The "Grisette.Unified" module offers an experimental unified interface for
  symbolic and concrete evaluation. This module should be imported qualified.
  .
  For more details, please checkout the README and 
  [tutorials](https://github.com/lsrcz/grisette/tree/main/tutorials).
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu, Rastislav Bodík"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette
copyright: "2021-2024 Sirui Lu"
extra-source-files:
  - CHANGELOG.md
  - README.md
tested-with:
  - GHC == 8.10.7
  - GHC == 9.0.2
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.6
  - GHC == 9.8.2
  - GHC == 9.10.1

dependencies:
  - base >= 4.14 && < 5
  - intern >= 0.9.2 && < 0.10
  - hashable >= 1.2.3 && < 1.6
  - mtl >= 2.2.2 && < 2.4
  - transformers >= 0.5.6 && < 0.7
  - generic-deriving >= 1.14.1 && < 1.15
  - bytestring >= 0.10.12 && < 0.13
  - containers >= 0.4 && < 0.8
  - unordered-containers >= 0.2.11 && < 0.3
  - template-haskell >= 2.16 && < 2.23
  - deepseq >= 1.4.4 && < 1.6
  - hashtables >= 1.2.3.4 && < 1.4
  - loch-th >= 0.2.2 && < 0.3
  - th-compat >= 0.1.2 && < 0.2
  - th-abstraction >= 0.4 && < 0.8
  - array >= 0.5.4 && < 0.6
  - sbv >= 8.17 && < 11
  - parallel >= 3.2.2.0 && < 3.3
  - text >= 1.2.4.1 && < 2.2
  - QuickCheck >= 2.14 && < 2.16
  - prettyprinter >= 1.5.0 && < 1.8
  - async >= 2.2.2 && < 2.3
  - stm >= 2.5 && < 2.6
  - libBF >= 0.6.3 && < 0.7

flags:
  {
    optimize:
      {
        description: "Compile with O2 optimization",
        manual: False,
        default: True,
      },
  }

when:
  - condition: flag(optimize)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options:
  - -Wextra
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wno-x-partial

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette
      - test-framework >= 0.8.2 && < 0.9
      - test-framework-hunit >= 0.3.0.2 && < 0.4
      - test-framework-quickcheck2 >= 0.3.0.5 && < 0.4
      - HUnit >= 1.6 && < 1.7
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wredundant-constraints
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - grisette
      - doctest >= 0.18.2 && < 0.23
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
