name: grisette
version: 0.3.1.0
synopsis: Symbolic evaluation as a library
description: |
  Grisette is a reusable symbolic evaluation library for Haskell. By
  translating programs into constraints, Grisette can help the development of
  program reasoning tools, including verification, synthesis, and more.
  .
  This "Grisette" module exports all you need for building a symbolic evaluation
  tool.
  .
  For more details, please checkout the README.
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu, Rastislav Bodík"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette
copyright: "2021-2023 Sirui Lu"
extra-source-files:
  - CHANGELOG.md
  - README.md
tested-with:
  - GHC == 8.10.7
  - GHC == 9.0.2
  - GHC == 9.2.8
  - GHC == 9.4.5
  - GHC == 9.6.2

dependencies:
  - base >= 4.14 && < 5
  - intern >= 0.9.2 && < 0.10
  - hashable >= 1.2.3 && < 1.5
  - mtl >= 2.2.2 && < 2.4
  - transformers >= 0.5.6 && < 0.7
  - generic-deriving >= 1.14.1 && < 1.15
  - bytestring >= 0.10.12 && < 0.12
  - unordered-containers >= 0.2.11 && < 0.3
  - template-haskell >= 2.16 && < 2.21
  - deepseq >= 1.4.4 && < 1.5
  - hashtables >= 1.2.3.4 && < 1.4
  - loch-th >= 0.2.2 && < 0.3
  - th-compat >= 0.1.2 && < 0.2
  - array >= 0.5.4 && < 0.6
  - sbv >= 8.11 && < 10.3
  - parallel >= 3.2.2.0 && < 3.3
  - text >= 1.2.4.1 && < 2.1
  - QuickCheck >= 2.13.2 && < 2.15
  - prettyprinter >= 1.5.0 && < 1.8

flags:
  {
    fast:
      {
        description: "Compile with O2 optimization",
        manual: False,
        default: True,
      },
  }

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options:
  - -Wextra
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wpartial-fields
  - -Wunused-type-patterns

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette
      - tasty >= 1.1.0.3 && < 1.5
      - tasty-hunit >= 0.10 && < 0.11
      - tasty-test-reporter >= 0.1.1.2 && < 0.2
      - tasty-quickcheck >= 0.10.1 && < 0.11
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - grisette
      - doctest >= 0.18.2 && < 0.22
      - Glob
