name: pizza-lib
version: 0.1.0.0
synopsis: Extra Pizza library
description: Extra Pizza library, data structures and lifted functions
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/pizza-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- pizza-core == 0.1.0.0
- pizza-symir == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src
