name: pizza-core
version: 0.1.0.0
synopsis: Monadic symbolic compilation
description: Monadic library for a symbolic host language in haskell
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/pizza-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- hashable >= 1.3
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- generic-deriving >= 1.14.1
- bytestring >= 0.10.12
- unordered-containers >= 0.2.11
- template-haskell >= 2.16
- deepseq >= 1.4.4
- hashtables >= 1.2.3.4
- loch-th >= 0.2.2
- th-compat >= 0.1.2
- hspec == 2.*
- hspec-junit-formatter >= 1.0.0.0

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - pizza-core
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover == 2.*
