name: grisette-doctest
version: 0.1.0.0
synopsis: Doctest for Grisette
description: Doctest for Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
  - base > 4.14 && < 5

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - intern >= 0.9.2 && < 0.10
      - hashable >= 1.3 && < 1.5
      - mtl >= 2.2.2 && < 2.3
      - transformers >= 0.5.6 && < 0.6
      - generic-deriving >= 1.14.1 && < 1.15
      - bytestring >= 0.10.12 && < 0.12
      - unordered-containers >= 0.2.11 && < 0.3
      - template-haskell >= 2.16 && < 2.20
      - deepseq >= 1.4.4 && < 1.5
      - vector >= 0.12.1 && < 0.14
      - hashtables >= 1.2.3 && < 1.5
      - loch-th >= 0.2.2 && < 0.3
      - array >= 0.5.4 && < 0.6
      - sbv >= 8.11 && < 9.1
      - th-compat >= 0.1.2 && < 0.2
      - once >= 0.2 && < 0.5
      - call-stack >= 0.1 && < 0.5
      - grisette-core == 0.1.0.0
      - grisette-symir == 0.1.0.0
      - grisette-backend-sbv == 0.1.0.0
      - grisette == 0.1.0.0
      - doctest >= 0.18.2 && < 0.21
      - Glob
