name: pizza-backend-sbv
version: 0.1.0.0
synopsis: Lowering symbolic primitives to SMT
description: Lowering symbolic primitives to SMT
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/pizza-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- pizza-core == 0.1.0.0
- pizza-symir == 0.1.0.0
- hashable >= 1.3
- mtl >= 2.2.2
- unordered-containers >= 0.2.11
- sbv >= 8.11
- template-haskell >= 2.16
- deepseq >= 1.4.4

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - pizza-backend-sbv
      - tasty >= 1.1.0.3
      - tasty-hunit >= 0.10
      - tasty-test-reporter >= 0.1.1.2
      - tasty-quickcheck >= 0.10.1
