name: pizza-symir
version: 0.1.0.0
synopsis: Symbolic IR
description: Default symbolic IR implementation for pizza
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/pizza-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- pizza-core == 0.1.0.0
- intern >= 0.9.2
- hashable >= 1.3
- mtl >= 2.2.2
- unordered-containers >= 0.2.11
- template-haskell >= 2.16
- deepseq >= 1.4.4
- array >= 0.5.4.0
- vector >= 0.12.1.2
- th-compat >= 0.1.2
- once >= 0.2

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main.hs
    dependencies:
      - pizza-symir
