name: grisette-backend-sbv
version: 0.1.0.0
synopsis: Lowering symbolic primitives to SMT
description: Lowering symbolic primitives to SMT
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- grisette-symir == 0.1.0.0
- hashable >= 1.3 && < 1.5
- mtl >= 2.2.2 && < 2.3
- unordered-containers >= 0.2.11 && < 0.3
- sbv >= 8.11 && < 9.1
- template-haskell >= 2.16 && < 2.20
- deepseq >= 1.4.4 && < 1.5

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette-backend-sbv
      - tasty >= 1.1.0.3 && < 1.5
      - tasty-hunit >= 0.10 && < 0.11
      - tasty-test-reporter >= 0.1.1.2 && < 0.2
      - tasty-quickcheck >= 0.10.1 && < 0.11
