name: Check format

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/run-ormolu@v11
      with:
        version: 0.6.0.1
